"""empty message

Revision ID: 63665f8a83e9
Revises: 10a83d6f3be4
Create Date: 2018-11-17 19:10:07.995389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63665f8a83e9'
down_revision = '10a83d6f3be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('poster', sa.Column('victim_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'poster', 'victim', ['victim_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'poster', type_='foreignkey')
    op.drop_column('poster', 'victim_id')
    # ### end Alembic commands ###
